---
- name: "Load lvm kernel modules"
  become: yes
  with_items:
      - "dm_snapshot"
      - "dm_mirror"
      - "dm_thin_pool"
  modprobe:
      name: "{{ item }}"
      state: "present"

- name: "Install glusterfs mount utils (RedHat)"
  become: yes
  yum:
      name: "glusterfs-fuse"
      state: "present"
  when: "ansible_os_family == 'RedHat'"

- name: "Install glusterfs mount utils (Debian)"
  become: yes
  apt:
      name: "glusterfs-client"
      state: "present"
  when: "ansible_os_family == 'Debian'"
