---
- name: install | Copy crictl binary from download dir
  copy:
    src: "{{ local_release_dir }}/{{ item }}"
    dest: "{{ bin_dir }}/{{ item }}"
    mode: 0755
    remote_src: yes
  with_items:
    - crictl
