#!/usr/bin/env bash
logfile=inventory/mycluster/artifacts/log.txt
scripts/my_playbook.sh --tags=client,netchecker,dashboard cluster.yml $* 2>> $logfile
# We check the kube-api cluster health with the following script that was generated by ansible.
inventory/mycluster/artifacts/kubectl.sh --namespace=kube-system apply --force --filename=inventory/mycluster/artifacts/dashboard.yml 2>> $logfile
inventory/mycluster/artifacts/kubectl.sh proxy &
sleep 10
curl -SL 127.0.0.1:8001/healthz
